### ISSUE TITLE
Слишком широкое "срабатывание" полосы быстрой прокрутки вверх

### ISSUE THREAD

**Issue by Andryshik345** [grin3671/shiki-theme#14]
На мониторе 4:3(1280x1024) слишком широкая полоса быстрой прокрутки, из-за чего нельзя нажать на короткие ссылки.
![screenshot_3](https://user-images.githubusercontent.com/24612088/38159858-59b00886-34cb-11e8-9b2c-0d8d4db2f783.jpg)
![screenshot_4](https://user-images.githubusercontent.com/24612088/38159859-59d6183c-34cb-11e8-81da-b6f18244458a.jpg)

**Comment by grin3671** [comment]
Мы решили эту проблему еще в b90c97c (#13), 43 коммита назад.
Вам стоит просто обновить стиль в сборщике. Напишите на сайте в [лс](https://shikimori.org/grin3671), если возникнут трудности.
