### ISSUE TITLE
Неправильное отображение некоторых всплывающих элементов профиля в вертикальной мобильной версии (Chrome, Firefox)

### ISSUE THREAD

**Issue by Ghosteon** [grin3671/shiki-theme#22]
**Разрешение экрана устройства, на котором делались скриншоты: 600x1024 (16:9)**
**Версия темы с тёмным оформлением: CSS Theme v1.2.84 (stable)**
**Версии браузеров:**
**- Google Chrome: 67.0.3396.87**
**- Firefox: 61.0**

При нажатии на элемент "member since" в Chrome вызывается горизонтальный скролл и смещаются элементы "поиск" и "аватар пользователя/иконка входа" вправо.
![1_st](https://user-images.githubusercontent.com/39534849/42344894-5eee7ca2-80a6-11e8-98e2-36395a5817a9.png)

С другими вариантами оформления аналогично.
![2_ed](https://user-images.githubusercontent.com/39534849/42344927-7dc66252-80a6-11e8-96cf-bdf41713becc.png)

На Firefox же такого нет, но при этом он обрезает часть всплывающего сообщения вместо того, чтобы включить скролл.
![3_mo](https://user-images.githubusercontent.com/39534849/42344980-acaff812-80a6-11e8-8023-e32059ba1721.png)

При нажатии на элемент "Also known as:" в Chrome также вызывается горизонтальный скролл и смещаются элементы "поиск" и "аватар пользователя/иконка входа" вправо.
![5_na](https://user-images.githubusercontent.com/39534849/42345267-72812bba-80a7-11e8-8389-3804b37a8bb5.png)

Если первая проблема (элемент member since) бывает только если не хватает места самому всплывающему элементу (то есть он не перенёсся на другую строку), то вторая (элемент Also known as:) есть всегда (до N разрешения). При этом на декстопе или в горизонтальном(альбомном) положении подобной проблемы нет.

**Comment by grin3671** [comment]
@Ghosteon, т.к. проблема есть и в стандартной версии, всё что я могу - убрать горизонтальный скролл и постараться вернуть элементу Also known as свойство `display: inline` (тут мой косяк). Была идея перевести эти всплывающие подсказки на CSS, но это не сильно исправит положение, к сожалению.

**Comment by Ghosteon** [comment]
@grin3671, а возможно ли применить к указанным элементам `position: absolute` и выводить подсказки в определённом месте? Если же нет, то, мне кажется, будет лучше просто обрезать всплывающие подсказки, то есть убирать горизонтальный скролл, как делает тот же Firefox, собственно делать то, что Вы уже написали. Но я CSS знаю не так хорошо, поэтому в данном случае я не более чем диванный эксперт.
