### ISSUE TITLE
Использовать крупные исходники для избранного

### ISSUE THREAD

**Issue by x9136** [grin3671/shiki-theme#53]
Привет! Если будет возможность, предлагаю использовать крупные исходники для избранного, чтобы оно не мылилось из-за растяжения мелких картинок на контейнер, который больше в несколько раз.

![Screenshot 2024-11-27 at 14 32 27](https://github.com/user-attachments/assets/d7531b10-5550-431b-9b60-7ed95e255ee7)

**Comment by grin3671** [comment]
Эта настройка находится во вкладке «Профиль» и называется «Улучшить качество картинок избранного в профиле». Насколько я знаю, никто не может поставить эту галочку, кроме владельца профиля. Ни в сборщике, ни в CSS это изменить нельзя, поэтому к теме, в общем-то, это не имеет никакого отношения. Я бы и рад, будь такая возможность, но пока могу только посоветовать читать FAQ в моём профиле: https://shikimori.one/grin3671

P.S. Делать OAuth 2.0 авторизацию в сборщике через аккаунт Шикимори тоже не вариант, потому что настройки пользователя таким образом нельзя поменять, хотя могу и ошибаться.

**Comment by x9136** [comment]
Например, в одном из приложений для Android улучшение качества картинок происходит через замену ссылки оригинала на крупный вариант.

Неожиданно, что в настройки сайта добавили подобный чекбокс. Логичней было бы добавить условие, даже не совсем точное, в духе: если спец. стиль активен, то тянуть крупные оригиналы.

**Comment by grin3671** [comment]
> в одном из приложений для Android

Приложения сами определяют структуру приложения и их внешний вид, обращаясь только к API сайта — это как если бы на Шикимори, помимо CSS, можно было бы редактировать HTML. Такой возможности нет, поэтому придумали галку.

Не все стили сложные, некоторые просто меняют фон или цвета, поэтому грузить огромные картинки только из-за наличия пользовательского стиля было бы чрезмерно, а любые сложные условия проверяющие селекторы, импорты и другие факторы кодить гораздо сложнее, чем добавить отдельную галочку для тех, кому это действительно необходимо.
